experiment:
    project: "textok_b32_vae"
    name: "textok_b32_vae_run1"
    output_dir: "textok_b32_vae_run1"
    max_train_examples: 685_800_000
    save_every: 10_000
    eval_every: 10_000
    generate_every: 10_000
    log_every: 50
    log_grad_norm_every: 1_000
    resume: True
    # init_tatitok: "../../textok-ckpts/tatitok_bl32_vae.pth"
model:
    vq_model:
        quantize_mode: vae
        token_size: 16
        # vit arch
        vit_enc_model_size: "base"
        vit_dec_model_size: "base"
        vit_enc_patch_size: 16
        vit_dec_patch_size: 16
        num_latent_tokens: 32
        finetune_decoder: False
        is_legacy: False
        text_embed_dim: 768 # clip embedding size

losses:
    discriminator_start: 200_000
    quantizer_weight: 1.0
    discriminator_factor: 1.0
    discriminator_weight: 0.1
    perceptual_loss: "lpips-convnext_s-1.0-0.1"
    perceptual_weight: 1.1
    reconstruction_loss: "l2"
    reconstruction_weight: 1.0
    lecam_regularization_weight: 0.001
    kl_weight: 1e-6
    logvar_init: 0.0

dataset:
    params:
        train_shards_path_or_url: "/data/san/HF_datasets/imgnet-1k-caption-wds/imagenet1k-train-{000000..000160}.tar"
        eval_shards_path_or_url: "/data/san/HF_datasets/imgnet-1k-caption-wds/imagenet1k-val-{000000..000049}.tar"
        # train_shards_path_or_url: "/home/ubuntu/textok-ckpts/wds_output/laion12m-train-{000000..000099}.tar"
        # eval_shards_path_or_url: "/home/ubuntu/textok-ckpts/wds_output/imagenet1k-val-{000000..000049}.tar"
        # num_workers_per_gpu: 12
        num_workers_per_gpu: 12
        dataset_with_class_label: False
        dataset_with_text_label: True
    preprocessing:
        resize_shorter_edge: 256
        crop_size: 256
        random_crop: True
        random_flip: True
        res_ratio_filtering: True

optimizer:
    name: adamw 
    params:
        learning_rate: 1e-4
        discriminator_learning_rate: 1e-4
        beta1: 0.9
        beta2: 0.999
        weight_decay: 1e-4

lr_scheduler:
    scheduler: "cosine"
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 10_000
        end_lr: 1e-5

training:
    gradient_accumulation_steps: 1
    per_gpu_batch_size: 8
    mixed_precision: "fp16"
    enable_tf32: True
    enable_wandb: True
    use_ema: True
    seed: 42
    max_train_steps: 350_000     # 650_000
    num_generated_images: 2
    max_grad_norm: 1.0